name = "test"
main = "dist/index.mjs"

workers_dev = false
account_id = "dc941e8156f4a1336ca08481cb6d4222"

usage_model = "bundled"

compatibility_date = "2022-09-14"
compatibility_flags = []

routes = [
	{ pattern = "testing.garretcharp.com", custom_domain = true }
]

[durable_objects]
bindings = [
	{ name = "TestDO", class_name = "TestDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["TestDO"]

[build]
command = "npm run build"
