name = "test"
main = "dist/index.mjs"

workers_dev = false
account_id = "dc941e8156f4a1336ca08481cb6d4222"

usage_model = "bundled"

compatibility_date = "2022-09-14"
compatibility_flags = []

routes = [
	{ pattern = "testing.garretcharp.com", custom_domain = true }
]

[durable_objects]
bindings = [
	{ name = "TestDO", class_name = "TestDO" },
	{ name = "ChatManager", class_name = "ChatManager" },
	{ name = "ChatNode", class_name = "ChatNode" }
]

[[ d1_databases ]]
binding = "TestD1"
database_name = "test-d1"
database_id = "aa6f2f3f-b483-437f-94b9-a9b932b83e65"

[[migrations]]
tag = "v1"
new_classes = ["TestDO"]

[[migrations]]
tag = "v2"
new_classes = ["ChatManager", "ChatNode"]

[build]
command = "npm run build"
